<?php 

return [ 
    'datos' => [
    array("c" => "fa-500px", "l" => "500px"),
    array("c" => "fa-adjust", "l" => "Adjust"),
    array("c" => "fa-adn", "l" => "Adn"),
    array("c" => "fa-align-center", "l" => "Align center"),
    array("c" => "fa-align-justify", "l" => "Align justify"),
    array("c" => "fa-align-left", "l" => "Align left"),
    array("c" => "fa-align-right", "l" => "Align right"),
    array("c" => "fa-amazon", "l" => "Amazon"),
    array("c" => "fa-ambulance", "l" => "Ambulance"),
    array("c" => "fa-anchor", "l" => "Anchor"),
    array("c" => "fa-android", "l" => "Android"),
    array("c" => "fa-angellist", "l" => "Angellist"),
    array("c" => "fa-angle-double-down", "l" => "Angle double down"),
    array("c" => "fa-angle-double-left", "l" => "Angle double left"),
    array("c" => "fa-angle-double-right", "l" => "Angle double right"),
    array("c" => "fa-angle-double-up", "l" => "Angle double up"),
    array("c" => "fa-angle-down", "l" => "Angle down"),
    array("c" => "fa-angle-left", "l" => "Angle left"),
    array("c" => "fa-angle-right", "l" => "Angle right"),
    array("c" => "fa-angle-up", "l" => "Angle up"),
    array("c" => "fa-apple", "l" => "Apple"),
    array("c" => "fa-archive", "l" => "Archive"),
    array("c" => "fa-area-chart", "l" => "Area chart"),
    array("c" => "fa-arrow-circle-down", "l" => "Arrow circle down"),
    array("c" => "fa-arrow-circle-left", "l" => "Arrow circle left"),
    array("c" => "fa-arrow-circle-o-down", "l" => "Arrow circle o down"),
    array("c" => "fa-arrow-circle-o-left", "l" => "Arrow circle o left"),
    array("c" => "fa-arrow-circle-o-right", "l" => "Arrow circle o right"),
    array("c" => "fa-arrow-circle-o-up", "l" => "Arrow circle o up"),
    array("c" => "fa-arrow-circle-right", "l" => "Arrow circle right"),
    array("c" => "fa-arrow-circle-up", "l" => "Arrow circle up"),
    array("c" => "fa-arrow-down", "l" => "Arrow down"),
    array("c" => "fa-arrow-left", "l" => "Arrow left"),
    array("c" => "fa-arrow-right", "l" => "Arrow right"),
    array("c" => "fa-arrow-up", "l" => "Arrow up"),
    array("c" => "fa-arrows", "l" => "Arrows"),
    array("c" => "fa-arrows-alt", "l" => "Arrows alt"),
    array("c" => "fa-arrows-h", "l" => "Arrows h"),
    array("c" => "fa-arrows-v", "l" => "Arrows v"),
    array("c" => "fa-asterisk", "l" => "Asterisk"),
    array("c" => "fa-at", "l" => "At"),
    array("c" => "fa-backward", "l" => "Backward"),
    array("c" => "fa-balance-scale", "l" => "Balance scale"),
    array("c" => "fa-ban", "l" => "Ban"),
    array("c" => "fa-bar-chart", "l" => "Bar chart"),
    array("c" => "fa-barcode", "l" => "Barcode"),
    array("c" => "fa-bars", "l" => "Bars"),
    array("c" => "fa-battery-empty", "l" => "Battery empty"),
    array("c" => "fa-battery-full", "l" => "Battery full"),
    array("c" => "fa-battery-half", "l" => "Battery half"),
    array("c" => "fa-battery-quarter", "l" => "Battery quarter"),
    array("c" => "fa-battery-three-quarters", "l" => "Battery three quarters"),
    array("c" => "fa-bed", "l" => "Bed"),
    array("c" => "fa-beer", "l" => "Beer"),
    array("c" => "fa-behance", "l" => "Behance"),
    array("c" => "fa-behance-square", "l" => "Behance square"),
    array("c" => "fa-bell", "l" => "Bell"),
    array("c" => "fa-bell-o", "l" => "Bell o"),
    array("c" => "fa-bell-slash", "l" => "Bell slash"),
    array("c" => "fa-bell-slash-o", "l" => "Bell slash o"),
    array("c" => "fa-bicycle", "l" => "Bicycle"),
    array("c" => "fa-binoculars", "l" => "Binoculars"),
    array("c" => "fa-birthday-cake", "l" => "Birthday cake"),
    array("c" => "fa-bitbucket", "l" => "Bitbucket"),
    array("c" => "fa-bitbucket-square", "l" => "Bitbucket square"),
    array("c" => "fa-black-tie", "l" => "Black tie"),
    array("c" => "fa-bold", "l" => "Bold"),
    array("c" => "fa-bolt", "l" => "Bolt"),
    array("c" => "fa-bomb", "l" => "Bomb"),
    array("c" => "fa-book", "l" => "Book"),
    array("c" => "fa-bookmark", "l" => "Bookmark"),
    array("c" => "fa-bookmark-o", "l" => "Bookmark o"),
    array("c" => "fa-briefcase", "l" => "Briefcase"),
    array("c" => "fa-btc", "l" => "Btc"),
    array("c" => "fa-bug", "l" => "Bug"),
    array("c" => "fa-building", "l" => "Building"),
    array("c" => "fa-building-o", "l" => "Building o"),
    array("c" => "fa-bullhorn", "l" => "Bullhorn"),
    array("c" => "fa-bullseye", "l" => "Bullseye"),
    array("c" => "fa-bus", "l" => "Bus"),
    array("c" => "fa-buysellads", "l" => "Buysellads"),
    array("c" => "fa-calculator", "l" => "Calculator"),
    array("c" => "fa-calendar", "l" => "Calendar"),
    array("c" => "fa-calendar-check-o", "l" => "Calendar check o"),
    array("c" => "fa-calendar-minus-o", "l" => "Calendar minus o"),
    array("c" => "fa-calendar-o", "l" => "Calendar o"),
    array("c" => "fa-calendar-plus-o", "l" => "Calendar plus o"),
    array("c" => "fa-calendar-times-o", "l" => "Calendar times o"),
    array("c" => "fa-camera", "l" => "Camera"),
    array("c" => "fa-camera-retro", "l" => "Camera retro"),
    array("c" => "fa-car", "l" => "Car"),
    array("c" => "fa-caret-down", "l" => "Caret down"),
    array("c" => "fa-caret-left", "l" => "Caret left"),
    array("c" => "fa-caret-right", "l" => "Caret right"),
    array("c" => "fa-caret-square-o-down", "l" => "Caret square o down"),
    array("c" => "fa-caret-square-o-left", "l" => "Caret square o left"),
    array("c" => "fa-caret-square-o-right", "l" => "Caret square o right"),
    array("c" => "fa-caret-square-o-up", "l" => "Caret square o up"),
    array("c" => "fa-caret-up", "l" => "Caret up"),
    array("c" => "fa-cart-arrow-down", "l" => "Cart arrow down"),
    array("c" => "fa-cart-plus", "l" => "Cart plus"),
    array("c" => "fa-cc", "l" => "Cc"),
    array("c" => "fa-cc-amex", "l" => "Cc amex"),
    array("c" => "fa-cc-diners-club", "l" => "Cc diners club"),
    array("c" => "fa-cc-discover", "l" => "Cc discover"),
    array("c" => "fa-cc-jcb", "l" => "Cc jcb"),
    array("c" => "fa-cc-mastercard", "l" => "Cc mastercard"),
    array("c" => "fa-cc-paypal", "l" => "Cc paypal"),
    array("c" => "fa-cc-stripe", "l" => "Cc stripe"),
    array("c" => "fa-cc-visa", "l" => "Cc visa"),
    array("c" => "fa-certificate", "l" => "Certificate"),
    array("c" => "fa-chain-broken", "l" => "Chain broken"),
    array("c" => "fa-check", "l" => "Check"),
    array("c" => "fa-check-circle", "l" => "Check circle"),
    array("c" => "fa-check-circle-o", "l" => "Check circle o"),
    array("c" => "fa-check-square", "l" => "Check square"),
    array("c" => "fa-check-square-o", "l" => "Check square o"),
    array("c" => "fa-chevron-circle-down", "l" => "Chevron circle down"),
    array("c" => "fa-chevron-circle-left", "l" => "Chevron circle left"),
    array("c" => "fa-chevron-circle-right", "l" => "Chevron circle right"),
    array("c" => "fa-chevron-circle-up", "l" => "Chevron circle up"),
    array("c" => "fa-chevron-down", "l" => "Chevron down"),
    array("c" => "fa-chevron-left", "l" => "Chevron left"),
    array("c" => "fa-chevron-right", "l" => "Chevron right"),
    array("c" => "fa-chevron-up", "l" => "Chevron up"),
    array("c" => "fa-child", "l" => "Child"),
    array("c" => "fa-chrome", "l" => "Chrome"),
    array("c" => "fa-circle", "l" => "Circle"),
    array("c" => "fa-circle-o", "l" => "Circle o"),
    array("c" => "fa-circle-o-notch", "l" => "Circle o notch"),
    array("c" => "fa-circle-thin", "l" => "Circle thin"),
    array("c" => "fa-clipboard", "l" => "Clipboard"),
    array("c" => "fa-clock-o", "l" => "Clock o"),
    array("c" => "fa-clone", "l" => "Clone"),
    array("c" => "fa-cloud", "l" => "Cloud"),
    array("c" => "fa-cloud-download", "l" => "Cloud download"),
    array("c" => "fa-cloud-upload", "l" => "Cloud upload"),
    array("c" => "fa-code", "l" => "Code"),
    array("c" => "fa-code-fork", "l" => "Code fork"),
    array("c" => "fa-codepen", "l" => "Codepen"),
    array("c" => "fa-coffee", "l" => "Coffee"),
    array("c" => "fa-cog", "l" => "Cog"),
    array("c" => "fa-cogs", "l" => "Cogs"),
    array("c" => "fa-columns", "l" => "Columns"),
    array("c" => "fa-comment", "l" => "Comment"),
    array("c" => "fa-comment-o", "l" => "Comment o"),
    array("c" => "fa-commenting", "l" => "Commenting"),
    array("c" => "fa-commenting-o", "l" => "Commenting o"),
    array("c" => "fa-comments", "l" => "Comments"),
    array("c" => "fa-comments-o", "l" => "Comments o"),
    array("c" => "fa-compass", "l" => "Compass"),
    array("c" => "fa-compress", "l" => "Compress"),
    array("c" => "fa-connectdevelop", "l" => "Connectdevelop"),
    array("c" => "fa-contao", "l" => "Contao"),
    array("c" => "fa-copyright", "l" => "Copyright"),
    array("c" => "fa-creative-commons", "l" => "Creative commons"),
    array("c" => "fa-credit-card", "l" => "Credit card"),
    array("c" => "fa-crop", "l" => "Crop"),
    array("c" => "fa-crosshairs", "l" => "Crosshairs"),
    array("c" => "fa-css3", "l" => "Css3"),
    array("c" => "fa-cube", "l" => "Cube"),
    array("c" => "fa-cubes", "l" => "Cubes"),
    array("c" => "fa-cutlery", "l" => "Cutlery"),
    array("c" => "fa-dashcube", "l" => "Dashcube"),
    array("c" => "fa-database", "l" => "Database"),
    array("c" => "fa-delicious", "l" => "Delicious"),
    array("c" => "fa-desktop", "l" => "Desktop"),
    array("c" => "fa-deviantart", "l" => "Deviantart"),
    array("c" => "fa-diamond", "l" => "Diamond"),
    array("c" => "fa-digg", "l" => "Digg"),
    array("c" => "fa-dot-circle-o", "l" => "Dot circle o"),
    array("c" => "fa-download", "l" => "Download"),
    array("c" => "fa-dribbble", "l" => "Dribbble"),
    array("c" => "fa-dropbox", "l" => "Dropbox"),
    array("c" => "fa-drupal", "l" => "Drupal"),
    array("c" => "fa-eject", "l" => "Eject"),
    array("c" => "fa-ellipsis-h", "l" => "Ellipsis h"),
    array("c" => "fa-ellipsis-v", "l" => "Ellipsis v"),
    array("c" => "fa-empire", "l" => "Empire"),
    array("c" => "fa-envelope", "l" => "Envelope"),
    array("c" => "fa-envelope-o", "l" => "Envelope o"),
    array("c" => "fa-envelope-square", "l" => "Envelope square"),
    array("c" => "fa-eraser", "l" => "Eraser"),
    array("c" => "fa-eur", "l" => "Eur"),
    array("c" => "fa-exchange", "l" => "Exchange"),
    array("c" => "fa-exclamation", "l" => "Exclamation"),
    array("c" => "fa-exclamation-circle", "l" => "Exclamation circle"),
    array("c" => "fa-exclamation-triangle", "l" => "Exclamation triangle"),
    array("c" => "fa-expand", "l" => "Expand"),
    array("c" => "fa-expeditedssl", "l" => "Expeditedssl"),
    array("c" => "fa-external-link", "l" => "External link"),
    array("c" => "fa-external-link-square", "l" => "External link square"),
    array("c" => "fa-eye", "l" => "Eye"),
    array("c" => "fa-eye-slash", "l" => "Eye slash"),
    array("c" => "fa-eyedropper", "l" => "Eyedropper"),
    array("c" => "fa-facebook", "l" => "Facebook"),
    array("c" => "fa-facebook-official", "l" => "Facebook official"),
    array("c" => "fa-facebook-square", "l" => "Facebook square"),
    array("c" => "fa-fast-backward", "l" => "Fast backward"),
    array("c" => "fa-fast-forward", "l" => "Fast forward"),
    array("c" => "fa-fax", "l" => "Fax"),
    array("c" => "fa-female", "l" => "Female"),
    array("c" => "fa-fighter-jet", "l" => "Fighter jet"),
    array("c" => "fa-file", "l" => "File"),
    array("c" => "fa-file-archive-o", "l" => "File archive o"),
    array("c" => "fa-file-audio-o", "l" => "File audio o"),
    array("c" => "fa-file-code-o", "l" => "File code o"),
    array("c" => "fa-file-excel-o", "l" => "File excel o"),
    array("c" => "fa-file-image-o", "l" => "File image o"),
    array("c" => "fa-file-o", "l" => "File o"),
    array("c" => "fa-file-pdf-o", "l" => "File pdf o"),
    array("c" => "fa-file-powerpoint-o", "l" => "File powerpoint o"),
    array("c" => "fa-file-text", "l" => "File text"),
    array("c" => "fa-file-text-o", "l" => "File text o"),
    array("c" => "fa-file-video-o", "l" => "File video o"),
    array("c" => "fa-file-word-o", "l" => "File word o"),
    array("c" => "fa-files-o", "l" => "Files o"),
    array("c" => "fa-film", "l" => "Film"),
    array("c" => "fa-filter", "l" => "Filter"),
    array("c" => "fa-fire", "l" => "Fire"),
    array("c" => "fa-fire-extinguisher", "l" => "Fire extinguisher"),
    array("c" => "fa-firefox", "l" => "Firefox"),
    array("c" => "fa-flag", "l" => "Flag"),
    array("c" => "fa-flag-checkered", "l" => "Flag checkered"),
    array("c" => "fa-flag-o", "l" => "Flag o"),
    array("c" => "fa-flask", "l" => "Flask"),
    array("c" => "fa-flickr", "l" => "Flickr"),
    array("c" => "fa-floppy-o", "l" => "Floppy o"),
    array("c" => "fa-folder", "l" => "Folder"),
    array("c" => "fa-folder-o", "l" => "Folder o"),
    array("c" => "fa-folder-open", "l" => "Folder open"),
    array("c" => "fa-folder-open-o", "l" => "Folder open o"),
    array("c" => "fa-font", "l" => "Font"),
    array("c" => "fa-fonticons", "l" => "Fonticons"),
    array("c" => "fa-forumbee", "l" => "Forumbee"),
    array("c" => "fa-forward", "l" => "Forward"),
    array("c" => "fa-foursquare", "l" => "Foursquare"),
    array("c" => "fa-frown-o", "l" => "Frown o"),
    array("c" => "fa-futbol-o", "l" => "Futbol o"),
    array("c" => "fa-gamepad", "l" => "Gamepad"),
    array("c" => "fa-gavel", "l" => "Gavel"),
    array("c" => "fa-gbp", "l" => "Gbp"),
    array("c" => "fa-genderless", "l" => "Genderless"),
    array("c" => "fa-get-pocket", "l" => "Get pocket"),
    array("c" => "fa-gg", "l" => "Gg"),
    array("c" => "fa-gg-circle", "l" => "Gg circle"),
    array("c" => "fa-gift", "l" => "Gift"),
    array("c" => "fa-git", "l" => "Git"),
    array("c" => "fa-git-square", "l" => "Git square"),
    array("c" => "fa-github", "l" => "Github"),
    array("c" => "fa-github-alt", "l" => "Github alt"),
    array("c" => "fa-github-square", "l" => "Github square"),
    array("c" => "fa-glass", "l" => "Glass"),
    array("c" => "fa-globe", "l" => "Globe"),
    array("c" => "fa-google", "l" => "Google"),
    array("c" => "fa-google-plus", "l" => "Google plus"),
    array("c" => "fa-google-plus-square", "l" => "Google plus square"),
    array("c" => "fa-google-wallet", "l" => "Google wallet"),
    array("c" => "fa-graduation-cap", "l" => "Graduation cap"),
    array("c" => "fa-gratipay", "l" => "Gratipay"),
    array("c" => "fa-h-square", "l" => "H square"),
    array("c" => "fa-hacker-news", "l" => "Hacker news"),
    array("c" => "fa-hand-lizard-o", "l" => "Hand lizard o"),
    array("c" => "fa-hand-o-down", "l" => "Hand o down"),
    array("c" => "fa-hand-o-left", "l" => "Hand o left"),
    array("c" => "fa-hand-o-right", "l" => "Hand o right"),
    array("c" => "fa-hand-o-up", "l" => "Hand o up"),
    array("c" => "fa-hand-paper-o", "l" => "Hand paper o"),
    array("c" => "fa-hand-peace-o", "l" => "Hand peace o"),
    array("c" => "fa-hand-pointer-o", "l" => "Hand pointer o"),
    array("c" => "fa-hand-rock-o", "l" => "Hand rock o"),
    array("c" => "fa-hand-scissors-o", "l" => "Hand scissors o"),
    array("c" => "fa-hand-spock-o", "l" => "Hand spock o"),
    array("c" => "fa-hdd-o", "l" => "Hdd o"),
    array("c" => "fa-header", "l" => "Header"),
    array("c" => "fa-headphones", "l" => "Headphones"),
    array("c" => "fa-heart", "l" => "Heart"),
    array("c" => "fa-heart-o", "l" => "Heart o"),
    array("c" => "fa-heartbeat", "l" => "Heartbeat"),
    array("c" => "fa-history", "l" => "History"),
    array("c" => "fa-home", "l" => "Home"),
    array("c" => "fa-hospital-o", "l" => "Hospital o"),
    array("c" => "fa-hourglass", "l" => "Hourglass"),
    array("c" => "fa-hourglass-end", "l" => "Hourglass end"),
    array("c" => "fa-hourglass-half", "l" => "Hourglass half"),
    array("c" => "fa-hourglass-o", "l" => "Hourglass o"),
    array("c" => "fa-hourglass-start", "l" => "Hourglass start"),
    array("c" => "fa-houzz", "l" => "Houzz"),
    array("c" => "fa-html5", "l" => "Html5"),
    array("c" => "fa-i-cursor", "l" => "I cursor"),
    array("c" => "fa-ils", "l" => "Ils"),
    array("c" => "fa-inbox", "l" => "Inbox"),
    array("c" => "fa-indent", "l" => "Indent"),
    array("c" => "fa-industry", "l" => "Industry"),
    array("c" => "fa-info", "l" => "Info"),
    array("c" => "fa-info-circle", "l" => "Info circle"),
    array("c" => "fa-inr", "l" => "Inr"),
    array("c" => "fa-instagram", "l" => "Instagram"),
    array("c" => "fa-internet-explorer", "l" => "Internet explorer"),
    array("c" => "fa-ioxhost", "l" => "Ioxhost"),
    array("c" => "fa-italic", "l" => "Italic"),
    array("c" => "fa-joomla", "l" => "Joomla"),
    array("c" => "fa-jpy", "l" => "Jpy"),
    array("c" => "fa-jsfiddle", "l" => "Jsfiddle"),
    array("c" => "fa-key", "l" => "Key"),
    array("c" => "fa-keyboard-o", "l" => "Keyboard o"),
    array("c" => "fa-krw", "l" => "Krw"),
    array("c" => "fa-language", "l" => "Language"),
    array("c" => "fa-laptop", "l" => "Laptop"),
    array("c" => "fa-lastfm", "l" => "Lastfm"),
    array("c" => "fa-lastfm-square", "l" => "Lastfm square"),
    array("c" => "fa-leaf", "l" => "Leaf"),
    array("c" => "fa-leanpub", "l" => "Leanpub"),
    array("c" => "fa-lemon-o", "l" => "Lemon o"),
    array("c" => "fa-level-down", "l" => "Level down"),
    array("c" => "fa-level-up", "l" => "Level up"),
    array("c" => "fa-life-ring", "l" => "Life ring"),
    array("c" => "fa-lightbulb-o", "l" => "Lightbulb o"),
    array("c" => "fa-line-chart", "l" => "Line chart"),
    array("c" => "fa-link", "l" => "Link"),
    array("c" => "fa-linkedin", "l" => "Linkedin"),
    array("c" => "fa-linkedin-square", "l" => "Linkedin square"),
    array("c" => "fa-linux", "l" => "Linux"),
    array("c" => "fa-list", "l" => "List"),
    array("c" => "fa-list-alt", "l" => "List alt"),
    array("c" => "fa-list-ol", "l" => "List ol"),
    array("c" => "fa-list-ul", "l" => "List ul"),
    array("c" => "fa-location-arrow", "l" => "Location arrow"),
    array("c" => "fa-lock", "l" => "Lock"),
    array("c" => "fa-long-arrow-down", "l" => "Long arrow down"),
    array("c" => "fa-long-arrow-left", "l" => "Long arrow left"),
    array("c" => "fa-long-arrow-right", "l" => "Long arrow right"),
    array("c" => "fa-long-arrow-up", "l" => "Long arrow up"),
    array("c" => "fa-magic", "l" => "Magic"),
    array("c" => "fa-magnet", "l" => "Magnet"),
    array("c" => "fa-male", "l" => "Male"),
    array("c" => "fa-map", "l" => "Map"),
    array("c" => "fa-map-marker", "l" => "Map marker"),
    array("c" => "fa-map-o", "l" => "Map o"),
    array("c" => "fa-map-pin", "l" => "Map pin"),
    array("c" => "fa-map-signs", "l" => "Map signs"),
    array("c" => "fa-mars", "l" => "Mars"),
    array("c" => "fa-mars-double", "l" => "Mars double"),
    array("c" => "fa-mars-stroke", "l" => "Mars stroke"),
    array("c" => "fa-mars-stroke-h", "l" => "Mars stroke h"),
    array("c" => "fa-mars-stroke-v", "l" => "Mars stroke v"),
    array("c" => "fa-maxcdn", "l" => "Maxcdn"),
    array("c" => "fa-meanpath", "l" => "Meanpath"),
    array("c" => "fa-medium", "l" => "Medium"),
    array("c" => "fa-medkit", "l" => "Medkit"),
    array("c" => "fa-meh-o", "l" => "Meh o"),
    array("c" => "fa-mercury", "l" => "Mercury"),
    array("c" => "fa-microphone", "l" => "Microphone"),
    array("c" => "fa-microphone-slash", "l" => "Microphone slash"),
    array("c" => "fa-minus", "l" => "Minus"),
    array("c" => "fa-minus-circle", "l" => "Minus circle"),
    array("c" => "fa-minus-square", "l" => "Minus square"),
    array("c" => "fa-minus-square-o", "l" => "Minus square o"),
    array("c" => "fa-mobile", "l" => "Mobile"),
    array("c" => "fa-money", "l" => "Money"),
    array("c" => "fa-moon-o", "l" => "Moon o"),
    array("c" => "fa-motorcycle", "l" => "Motorcycle"),
    array("c" => "fa-mouse-pointer", "l" => "Mouse pointer"),
    array("c" => "fa-music", "l" => "Music"),
    array("c" => "fa-neuter", "l" => "Neuter"),
    array("c" => "fa-newspaper-o", "l" => "Newspaper o"),
    array("c" => "fa-object-group", "l" => "Object group"),
    array("c" => "fa-object-ungroup", "l" => "Object ungroup"),
    array("c" => "fa-odnoklassniki", "l" => "Odnoklassniki"),
    array("c" => "fa-odnoklassniki-square", "l" => "Odnoklassniki square"),
    array("c" => "fa-opencart", "l" => "Opencart"),
    array("c" => "fa-openid", "l" => "Openid"),
    array("c" => "fa-opera", "l" => "Opera"),
    array("c" => "fa-optin-monster", "l" => "Optin monster"),
    array("c" => "fa-outdent", "l" => "Outdent"),
    array("c" => "fa-pagelines", "l" => "Pagelines"),
    array("c" => "fa-paint-brush", "l" => "Paint brush"),
    array("c" => "fa-paper-plane", "l" => "Paper plane"),
    array("c" => "fa-paper-plane-o", "l" => "Paper plane o"),
    array("c" => "fa-paperclip", "l" => "Paperclip"),
    array("c" => "fa-paragraph", "l" => "Paragraph"),
    array("c" => "fa-pause", "l" => "Pause"),
    array("c" => "fa-paw", "l" => "Paw"),
    array("c" => "fa-paypal", "l" => "Paypal"),
    array("c" => "fa-pencil", "l" => "Pencil"),
    array("c" => "fa-pencil-square", "l" => "Pencil square"),
    array("c" => "fa-pencil-square-o", "l" => "Pencil square o"),
    array("c" => "fa-phone", "l" => "Phone"),
    array("c" => "fa-phone-square", "l" => "Phone square"),
    array("c" => "fa-picture-o", "l" => "Picture o"),
    array("c" => "fa-pie-chart", "l" => "Pie chart"),
    array("c" => "fa-pied-piper", "l" => "Pied piper"),
    array("c" => "fa-pied-piper-alt", "l" => "Pied piper alt"),
    array("c" => "fa-pinterest", "l" => "Pinterest"),
    array("c" => "fa-pinterest-p", "l" => "Pinterest p"),
    array("c" => "fa-pinterest-square", "l" => "Pinterest square"),
    array("c" => "fa-plane", "l" => "Plane"),
    array("c" => "fa-play", "l" => "Play"),
    array("c" => "fa-play-circle", "l" => "Play circle"),
    array("c" => "fa-play-circle-o", "l" => "Play circle o"),
    array("c" => "fa-plug", "l" => "Plug"),
    array("c" => "fa-plus", "l" => "Plus"),
    array("c" => "fa-plus-circle", "l" => "Plus circle"),
    array("c" => "fa-plus-square", "l" => "Plus square"),
    array("c" => "fa-plus-square-o", "l" => "Plus square o"),
    array("c" => "fa-power-off", "l" => "Power off"),
    array("c" => "fa-print", "l" => "Print"),
    array("c" => "fa-puzzle-piece", "l" => "Puzzle piece"),
    array("c" => "fa-qq", "l" => "Qq"),
    array("c" => "fa-qrcode", "l" => "Qrcode"),
    array("c" => "fa-question", "l" => "Question"),
    array("c" => "fa-question-circle", "l" => "Question circle"),
    array("c" => "fa-quote-left", "l" => "Quote left"),
    array("c" => "fa-quote-right", "l" => "Quote right"),
    array("c" => "fa-random", "l" => "Random"),
    array("c" => "fa-rebel", "l" => "Rebel"),
    array("c" => "fa-recycle", "l" => "Recycle"),
    array("c" => "fa-reddit", "l" => "Reddit"),
    array("c" => "fa-reddit-square", "l" => "Reddit square"),
    array("c" => "fa-refresh", "l" => "Refresh"),
    array("c" => "fa-registered", "l" => "Registered"),
    array("c" => "fa-renren", "l" => "Renren"),
    array("c" => "fa-repeat", "l" => "Repeat"),
    array("c" => "fa-reply", "l" => "Reply"),
    array("c" => "fa-reply-all", "l" => "Reply all"),
    array("c" => "fa-retweet", "l" => "Retweet"),
    array("c" => "fa-road", "l" => "Road"),
    array("c" => "fa-rocket", "l" => "Rocket"),
    array("c" => "fa-rss", "l" => "Rss"),
    array("c" => "fa-rss-square", "l" => "Rss square"),
    array("c" => "fa-rub", "l" => "Rub"),
    array("c" => "fa-safari", "l" => "Safari"),
    array("c" => "fa-scissors", "l" => "Scissors"),
    array("c" => "fa-search", "l" => "Search"),
    array("c" => "fa-search-minus", "l" => "Search minus"),
    array("c" => "fa-search-plus", "l" => "Search plus"),
    array("c" => "fa-sellsy", "l" => "Sellsy"),
    array("c" => "fa-server", "l" => "Server"),
    array("c" => "fa-share", "l" => "Share"),
    array("c" => "fa-share-alt", "l" => "Share alt"),
    array("c" => "fa-share-alt-square", "l" => "Share alt square"),
    array("c" => "fa-share-square", "l" => "Share square"),
    array("c" => "fa-share-square-o", "l" => "Share square o"),
    array("c" => "fa-shield", "l" => "Shield"),
    array("c" => "fa-ship", "l" => "Ship"),
    array("c" => "fa-shirtsinbulk", "l" => "Shirtsinbulk"),
    array("c" => "fa-shopping-cart", "l" => "Shopping cart"),
    array("c" => "fa-sign-in", "l" => "Sign in"),
    array("c" => "fa-sign-out", "l" => "Sign out"),
    array("c" => "fa-signal", "l" => "Signal"),
    array("c" => "fa-simplybuilt", "l" => "Simplybuilt"),
    array("c" => "fa-sitemap", "l" => "Sitemap"),
    array("c" => "fa-skyatlas", "l" => "Skyatlas"),
    array("c" => "fa-skype", "l" => "Skype"),
    array("c" => "fa-slack", "l" => "Slack"),
    array("c" => "fa-sliders", "l" => "Sliders"),
    array("c" => "fa-slideshare", "l" => "Slideshare"),
    array("c" => "fa-smile-o", "l" => "Smile o"),
    array("c" => "fa-sort", "l" => "Sort"),
    array("c" => "fa-sort-alpha-asc", "l" => "Sort alpha asc"),
    array("c" => "fa-sort-alpha-desc", "l" => "Sort alpha desc"),
    array("c" => "fa-sort-amount-asc", "l" => "Sort amount asc"),
    array("c" => "fa-sort-amount-desc", "l" => "Sort amount desc"),
    array("c" => "fa-sort-asc", "l" => "Sort asc"),
    array("c" => "fa-sort-desc", "l" => "Sort desc"),
    array("c" => "fa-sort-numeric-asc", "l" => "Sort numeric asc"),
    array("c" => "fa-sort-numeric-desc", "l" => "Sort numeric desc"),
    array("c" => "fa-soundcloud", "l" => "Soundcloud"),
    array("c" => "fa-space-shuttle", "l" => "Space shuttle"),
    array("c" => "fa-spinner", "l" => "Spinner"),
    array("c" => "fa-spoon", "l" => "Spoon"),
    array("c" => "fa-spotify", "l" => "Spotify"),
    array("c" => "fa-square", "l" => "Square"),
    array("c" => "fa-square-o", "l" => "Square o"),
    array("c" => "fa-stack-exchange", "l" => "Stack exchange"),
    array("c" => "fa-stack-overflow", "l" => "Stack overflow"),
    array("c" => "fa-star", "l" => "Star"),
    array("c" => "fa-star-half", "l" => "Star half"),
    array("c" => "fa-star-half-o", "l" => "Star half o"),
    array("c" => "fa-star-o", "l" => "Star o"),
    array("c" => "fa-steam", "l" => "Steam"),
    array("c" => "fa-steam-square", "l" => "Steam square"),
    array("c" => "fa-step-backward", "l" => "Step backward"),
    array("c" => "fa-step-forward", "l" => "Step forward"),
    array("c" => "fa-stethoscope", "l" => "Stethoscope"),
    array("c" => "fa-sticky-note", "l" => "Sticky note"),
    array("c" => "fa-sticky-note-o", "l" => "Sticky note o"),
    array("c" => "fa-stop", "l" => "Stop"),
    array("c" => "fa-street-view", "l" => "Street view"),
    array("c" => "fa-strikethrough", "l" => "Strikethrough"),
    array("c" => "fa-stumbleupon", "l" => "Stumbleupon"),
    array("c" => "fa-stumbleupon-circle", "l" => "Stumbleupon circle"),
    array("c" => "fa-subscript", "l" => "Subscript"),
    array("c" => "fa-subway", "l" => "Subway"),
    array("c" => "fa-suitcase", "l" => "Suitcase"),
    array("c" => "fa-sun-o", "l" => "Sun o"),
    array("c" => "fa-superscript", "l" => "Superscript"),
    array("c" => "fa-table", "l" => "Table"),
    array("c" => "fa-tablet", "l" => "Tablet"),
    array("c" => "fa-tachometer", "l" => "Tachometer"),
    array("c" => "fa-tag", "l" => "Tag"),
    array("c" => "fa-tags", "l" => "Tags"),
    array("c" => "fa-tasks", "l" => "Tasks"),
    array("c" => "fa-taxi", "l" => "Taxi"),
    array("c" => "fa-television", "l" => "Television"),
    array("c" => "fa-tencent-weibo", "l" => "Tencent weibo"),
    array("c" => "fa-terminal", "l" => "Terminal"),
    array("c" => "fa-text-height", "l" => "Text height"),
    array("c" => "fa-text-width", "l" => "Text width"),
    array("c" => "fa-th", "l" => "Th"),
    array("c" => "fa-th-large", "l" => "Th large"),
    array("c" => "fa-th-list", "l" => "Th list"),
    array("c" => "fa-thumb-tack", "l" => "Thumb tack"),
    array("c" => "fa-thumbs-down", "l" => "Thumbs down"),
    array("c" => "fa-thumbs-o-down", "l" => "Thumbs o down"),
    array("c" => "fa-thumbs-o-up", "l" => "Thumbs o up"),
    array("c" => "fa-thumbs-up", "l" => "Thumbs up"),
    array("c" => "fa-ticket", "l" => "Ticket"),
    array("c" => "fa-times", "l" => "Times"),
    array("c" => "fa-times-circle", "l" => "Times circle"),
    array("c" => "fa-times-circle-o", "l" => "Times circle o"),
    array("c" => "fa-tint", "l" => "Tint"),
    array("c" => "fa-toggle-off", "l" => "Toggle off"),
    array("c" => "fa-toggle-on", "l" => "Toggle on"),
    array("c" => "fa-trademark", "l" => "Trademark"),
    array("c" => "fa-train", "l" => "Train"),
    array("c" => "fa-transgender", "l" => "Transgender"),
    array("c" => "fa-transgender-alt", "l" => "Transgender alt"),
    array("c" => "fa-trash", "l" => "Trash"),
    array("c" => "fa-trash-o", "l" => "Trash o"),
    array("c" => "fa-tree", "l" => "Tree"),
    array("c" => "fa-trello", "l" => "Trello"),
    array("c" => "fa-tripadvisor", "l" => "Tripadvisor"),
    array("c" => "fa-trophy", "l" => "Trophy"),
    array("c" => "fa-truck", "l" => "Truck"),
    array("c" => "fa-try", "l" => "Try"),
    array("c" => "fa-tty", "l" => "Tty"),
    array("c" => "fa-tumblr", "l" => "Tumblr"),
    array("c" => "fa-tumblr-square", "l" => "Tumblr square"),
    array("c" => "fa-twitch", "l" => "Twitch"),
    array("c" => "fa-twitter", "l" => "Twitter"),
    array("c" => "fa-twitter-square", "l" => "Twitter square"),
    array("c" => "fa-umbrella", "l" => "Umbrella"),
    array("c" => "fa-underline", "l" => "Underline"),
    array("c" => "fa-undo", "l" => "Undo"),
    array("c" => "fa-university", "l" => "University"),
    array("c" => "fa-unlock", "l" => "Unlock"),
    array("c" => "fa-unlock-alt", "l" => "Unlock alt"),
    array("c" => "fa-upload", "l" => "Upload"),
    array("c" => "fa-usd", "l" => "Usd"),
    array("c" => "fa-user", "l" => "User"),
    array("c" => "fa-user-md", "l" => "User md"),
    array("c" => "fa-user-plus", "l" => "User plus"),
    array("c" => "fa-user-secret", "l" => "User secret"),
    array("c" => "fa-user-times", "l" => "User times"),
    array("c" => "fa-users", "l" => "Users"),
    array("c" => "fa-venus", "l" => "Venus"),
    array("c" => "fa-venus-double", "l" => "Venus double"),
    array("c" => "fa-venus-mars", "l" => "Venus mars"),
    array("c" => "fa-viacoin", "l" => "Viacoin"),
    array("c" => "fa-video-camera", "l" => "Video camera"),
    array("c" => "fa-vimeo", "l" => "Vimeo"),
    array("c" => "fa-vimeo-square", "l" => "Vimeo square"),
    array("c" => "fa-vine", "l" => "Vine"),
    array("c" => "fa-vk", "l" => "Vk"),
    array("c" => "fa-volume-down", "l" => "Volume down"),
    array("c" => "fa-volume-off", "l" => "Volume off"),
    array("c" => "fa-volume-up", "l" => "Volume up"),
    array("c" => "fa-weibo", "l" => "Weibo"),
    array("c" => "fa-weixin", "l" => "Weixin"),
    array("c" => "fa-whatsapp", "l" => "Whatsapp"),
    array("c" => "fa-wheelchair", "l" => "Wheelchair"),
    array("c" => "fa-wifi", "l" => "Wifi"),
    array("c" => "fa-wikipedia-w", "l" => "Wikipedia w"),
    array("c" => "fa-windows", "l" => "Windows"),
    array("c" => "fa-wordpress", "l" => "Wordpress"),
    array("c" => "fa-wrench", "l" => "Wrench"),
    array("c" => "fa-xing", "l" => "Xing"),
    array("c" => "fa-xing-square", "l" => "Xing square"),
    array("c" => "fa-y-combinator", "l" => "Y combinator"),
    array("c" => "fa-yahoo", "l" => "Yahoo"),
    array("c" => "fa-yelp", "l" => "Yelp"),
    array("c" => "fa-youtube", "l" => "Youtube"),
    array("c" => "fa-youtube-play", "l" => "Youtube play"),
    array("c" => "fa-youtube-square", "l" => "Youtube square")
]
];